# ETL Pipeline Preparation
Follow the instructions below to help you create your ETL pipeline.
### 1. Import libraries and load datasets.
- Import Python libraries
- Load `messages.csv` into a dataframe and inspect the first few lines.
- Load `categories.csv` into a dataframe and inspect the first few lines.

In [25]:
# import libraries

import numpy as np
import pandas as pd
import sqlalchemy

from sqlalchemy import create_engine

In [26]:
# load messages dataset
messages = pd.read_csv('../home/messages.csv')
messages.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [27]:
# load categories dataset
categories = pd.read_csv('../home/categories.csv')
categories.head()

   id                                         categories
0   2  related-1;request-0;offer-0;aid_related-0;medi...
1   7  related-1;request-0;offer-0;aid_related-1;medi...
2   8  related-1;request-0;offer-0;aid_related-0;medi...
3   9  related-1;request-1;offer-0;aid_related-1;medi...
4  12  related-1;request-0;offer-0;aid_related-0;medi...

### 2. Merge datasets.
- Merge the messages and categories datasets using the common id
- Assign this combined dataset to `df`, which will be cleaned in the following steps

In [28]:
# merge datasets
df = messages.merge(categories, on='id')
df.head()

,id,message,original,genre,categories
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,related-1;request-0;offer-0;aid_related-0;medi...
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,related-1;request-0;offer-0;aid_related-1;medi...
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,related-1;request-0;offer-0;aid_related-0;medi...
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,related-1;request-1;offer-0;aid_related-1;medi...
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,related-1;request-0;offer-0;aid_related-0;medi...

### 3. Split `categories` into separate category columns.
- Split the values in the `categories` column on the `;` character so that each value becomes a separate column. You'll find [this method](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Series.str.split.html) very helpful! Make sure to set `expand=True`.
- Use the first row of categories dataframe to create column names for the categories data.
- Rename columns of `categories` with new column names.

In [29]:
df['categories'].nunique()

4003

In [30]:
# create a dataframe of the 36 individual category columns
categories = df['categories'].str.split(';', expand=True)
categories.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

In [31]:
name_extract = lambda x:x.split('-')[0]

In [32]:
# select the first row of the categories dataframe
row = categories.iloc[0,:]

# use this row to extract a list of new column names for categories.
# one way is to apply a lambda function that takes everything 
# up to the second to last character of each string with slicing
category_colnames = list(categories.iloc[0,:].apply(name_extract))
print(category_colnames)

['related', 'request', 'offer', 'aid_related', 'medical_help', 'medical_products', 'search_and_rescue', 'security', 'military', 'child_alone', 'water', 'food', 'shelter', 'clothing', 'money', 'missing_people', 'refugees', 'death', 'other_aid', 'infrastructure_related', 'transport', 'buildings', 'electricity', 'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure', 'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold', 'other_weather', 'direct_report']

In [33]:
len(category_colnames)

36

In [34]:
# rename the columns of `categories`
categories.columns = category_colnames
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

### 4. Convert category values to just numbers 0 or 1.
- Iterate through the category columns in df to keep only the last character of each string (the 1 or 0). For example, `related-0` becomes `0`, `related-1` becomes `1`. Convert the string to a numeric value.
- You can perform [normal string actions on Pandas Series](https://pandas.pydata.org/pandas-docs/stable/text.html#indexing-with-str), like indexing, by including `.str` after the Series. You may need to first convert the Series to be of type string, which you can do with `astype(str)`.

In [35]:
categories.columns

Index(['related', 'request', 'offer', 'aid_related', 'medical_help',
       'medical_products', 'search_and_rescue', 'security', 'military',
       'child_alone', 'water', 'food', 'shelter', 'clothing', 'money',
       'missing_people', 'refugees', 'death', 'other_aid',
       'infrastructure_related', 'transport', 'buildings', 'electricity',
       'tools', 'hospitals', 'shops', 'aid_centers', 'other_infrastructure',
       'weather_related', 'floods', 'storm', 'fire', 'earthquake', 'cold',
       'other_weather', 'direct_report'],
      dtype='object')

In [36]:
extract_bool = lambda x:x[-1]

In [37]:
for column in categories:
    print(categories[column])

0        related-1
1        related-1
2        related-1
3        related-1
4        related-1
5        related-0
6        related-1
7        related-1
8        related-0
9        related-1
10       related-1
11       related-0
12       related-1
13       related-1
14       related-1
15       related-1
16       related-1
17       related-0
18       related-0
19       related-1
20       related-1
21       related-1
22       related-1
23       related-1
24       related-1
25       related-0
26       related-1
27       related-1
28       related-1
29       related-1
           ...
26356    related-1
26357    related-1
26358    related-1
26359    related-0
26360    related-0
26361    related-1
26362    related-1
26363    related-1
26364    related-1
26365    related-0
26366    related-1
26367    related-1
26368    related-1
26369    related-1
26370    related-0
26371    related-1
26372    related-1
26373    related-1
26374    related-0
26375    related-1
26376    related-1
26377    related-1
26378    related-1
26379    related-0
26380    related-1
26381    related-0
26382    related-0
26383    related-1
26384    related-1
26385    related-1
Name: related, Length: 26386, dtype: object
0        request-0
1        request-0
2        request-0
3        request-1
4        request-0
5        request-0
6        request-0
7        request-1
8        request-0
9        request-1
10       request-1
11       request-0
12       request-1
13       request-1
14       request-0
15       request-1
16       request-1
17       request-0
18       request-0
19       request-0
20       request-0
21       request-1
22       request-1
23       request-1
24       request-0
25       request-0
26       request-1
27       request-1
28       request-1
29       request-1
           ...
26356    request-0
26357    request-0
26358    request-0
26359    request-0
26360    request-0
26361    request-0
26362    request-0
26363    request-0
26364    request-0
26365    request-0
26366    request-0
26367    request-0
26368    request-0
26369    request-0
26370    request-0
26371    request-0
26372    request-0
26373    request-0
26374    request-0
26375    request-0
26376    request-0
26377    request-1
26378    request-0
26379    request-0
26380    request-0
26381    request-0
26382    request-0
26383    request-0
26384    request-0
26385    request-0
Name: request, Length: 26386, dtype: object
0        offer-0
1        offer-0
2        offer-0
3        offer-0
4        offer-0
5        offer-0
6        offer-0
7        offer-0
8        offer-0
9        offer-0
10       offer-0
11       offer-0
12       offer-0
13       offer-0
14       offer-0
15       offer-0
16       offer-0
17       offer-0
18       offer-0
19       offer-0
20       offer-0
21       offer-0
22       offer-0
23       offer-0
24       offer-0
25       offer-0
26       offer-0
27       offer-0
28       offer-0
29       offer-0
          ...
26356    offer-0
26357    offer-0
26358    offer-0
26359    offer-0
26360    offer-0
26361    offer-0
26362    offer-0
26363    offer-0
26364    offer-0
26365    offer-0
26366    offer-0
26367    offer-0
26368    offer-0
26369    offer-0
26370    offer-0
26371    offer-0
26372    offer-0
26373    offer-0
26374    offer-0
26375    offer-0
26376    offer-0
26377    offer-0
26378    offer-0
26379    offer-0
26380    offer-0
26381    offer-0
26382    offer-0
26383    offer-0
26384    offer-0
26385    offer-0
Name: offer, Length: 26386, dtype: object
0        aid_related-0
1        aid_related-1
2        aid_related-0
3        aid_related-1
4        aid_related-0
5        aid_related-0
6        aid_related-0
7        aid_related-1
8        aid_related-0
9        aid_related-1
10       aid_related-1
11       aid_related-0
12       aid_related-1
13       aid_related-1
14       aid_related-0
15       aid_related-1
16       aid_related-1
17       aid_related-0
18       aid_related-0
19       aid_related-0
20       aid_related-0
21       aid_related-1
22       aid_related-1
23       aid_related-1
24       aid_related-0
25       aid_related-0
26       aid_related-1
27       aid_related-1
28       aid_related-1
29       aid_related-1
             ...
26356    aid_related-1
26357    aid_related-1
26358    aid_related-1
26359    aid_related-0
26360    aid_related-0
26361    aid_related-1
26362    aid_related-0
26363    aid_related-1
26364    aid_related-0
26365    aid_related-0
26366    aid_related-0
26367    aid_related-1
26368    aid_related-1
26369    aid_related-1
26370    aid_related-0
26371    aid_related-0
26372    aid_related-0
26373    aid_related-1
26374    aid_related-0
26375    aid_related-1
26376    aid_related-1
26377    aid_related-0
26378    aid_related-0
26379    aid_related-0
26380    aid_related-0
26381    aid_related-0
26382    aid_related-0
26383    aid_related-0
26384    aid_related-1
26385    aid_related-0
Name: aid_related, Length: 26386, dtype: object
0        medical_help-0
1        medical_help-0
2        medical_help-0
3        medical_help-0
4        medical_help-0
5        medical_help-0
6        medical_help-0
7        medical_help-0
8        medical_help-0
9        medical_help-1
10       medical_help-1
11       medical_help-0
12       medical_help-0
13       medical_help-0
14       medical_help-0
15       medical_help-0
16       medical_help-1
17       medical_help-0
18       medical_help-0
19       medical_help-0
20       medical_help-0
21       medical_help-0
22       medical_help-0
23       medical_help-0
24       medical_help-0
25       medical_help-0
26       medical_help-1
27       medical_help-1
28       medical_help-0
29       medical_help-0
              ...
26356    medical_help-1
26357    medical_help-0
26358    medical_help-0
26359    medical_help-0
26360    medical_help-0
26361    medical_help-0
26362    medical_help-0
26363    medical_help-0
26364    medical_help-0
26365    medical_help-0
26366    medical_help-0
26367    medical_help-0
26368    medical_help-0
26369    medical_help-0
26370    medical_help-0
26371    medical_help-0
26372    medical_help-0
26373    medical_help-0
26374    medical_help-0
26375    medical_help-1
26376    medical_help-0
26377    medical_help-0
26378    medical_help-0
26379    medical_help-0
26380    medical_help-0
26381    medical_help-0
26382    medical_help-0
26383    medical_help-0
26384    medical_help-0
26385    medical_help-0
Name: medical_help, Length: 26386, dtype: object
0        medical_products-0
1        medical_products-0
2        medical_products-0
3        medical_products-1
4        medical_products-0
5        medical_products-0
6        medical_products-0
7        medical_products-0
8        medical_products-0
9        medical_products-1
10       medical_products-1
11       medical_products-0
12       medical_products-0
13       medical_products-0
14       medical_products-0
15       medical_products-1
16       medical_products-0
17       medical_products-0
18       medical_products-0
19       medical_products-0
20       medical_products-0
21       medical_products-0
22       medical_products-0
23       medical_products-0
24       medical_products-0
25       medical_products-0
26       medical_products-1
27       medical_products-0
28       medical_products-0
29       medical_products-0
                ...
26356    medical_products-0
26357    medical_products-1
26358    medical_products-0
26359    medical_products-0
26360    medical_products-0
26361    medical_products-0
26362    medical_products-0
26363    medical_products-0
26364    medical_products-0
26365    medical_products-0
26366    medical_products-0
26367    medical_products-0
26368    medical_products-1
26369    medical_products-0
26370    medical_products-0
26371    medical_products-0
26372    medical_products-0
26373    medical_products-0
26374    medical_products-0
26375    medical_products-1
26376    medical_products-0
26377    medical_products-0
26378    medical_products-0
26379    medical_products-0
26380    medical_products-0
26381    medical_products-0
26382    medical_products-0
26383    medical_products-0
26384    medical_products-0
26385    medical_products-0
Name: medical_products, Length: 26386, dtype: object
0        search_and_rescue-0
1        search_and_rescue-0
2        search_and_rescue-0
3        search_and_rescue-0
4        search_and_rescue-0
5        search_and_rescue-0
6        search_and_rescue-0
7        search_and_rescue-0
8        search_and_rescue-0
9        search_and_rescue-0
10       search_and_rescue-0
11       search_and_rescue-0
12       search_and_rescue-0
13       search_and_rescue-0
14       search_and_rescue-0
15       search_and_rescue-0
16       search_and_rescue-0
17       search_and_rescue-0
18       search_and_rescue-0
19       search_and_rescue-0
20       search_and_rescue-0
21       search_and_rescue-0
22       search_and_rescue-0
23       search_and_rescue-0
24       search_and_rescue-0
25       search_and_rescue-0
26       search_and_rescue-0
27       search_and_rescue-0
28       search_and_rescue-0
29       search_and_rescue-0
                ...
26356    search_and_rescue-0
26357    search_and_rescue-0
26358    search_and_rescue-0
26359    search_and_rescue-0
26360    search_and_rescue-0
26361    search_and_rescue-0
26362    search_and_rescue-0
26363    search_and_rescue-0
26364    search_and_rescue-0
26365    search_and_rescue-0
26366    search_and_rescue-0
26367    search_and_rescue-1
26368    search_and_rescue-0
26369    search_and_rescue-0
26370    search_and_rescue-0
26371    search_and_rescue-0
26372    search_and_rescue-0
26373    search_and_rescue-0
26374    search_and_rescue-0
26375    search_and_rescue-0
26376    search_and_rescue-0
26377    search_and_rescue-0
26378    search_and_rescue-0
26379    search_and_rescue-0
26380    search_and_rescue-0
26381    search_and_rescue-0
26382    search_and_rescue-0
26383    search_and_rescue-0
26384    search_and_rescue-0
26385    search_and_rescue-0
Name: search_and_rescue, Length: 26386, dtype: object
0        security-0
1        security-0
2        security-0
3        security-0
4        security-0
5        security-0
6        security-0
7        security-0
8        security-0
9        security-0
10       security-0
11       security-0
12       security-0
13       security-0
14       security-0
15       security-0
16       security-0
17       security-0
18       security-0
19       security-0
20       security-0
21       security-0
22       security-0
23       security-0
24       security-0
25       security-0
26       security-0
27       security-0
28       security-0
29       security-0
            ...
26356    security-0
26357    security-0
26358    security-0
26359    security-0
26360    security-0
26361    security-0
26362    security-0
26363    security-0
26364    security-0
26365    security-0
26366    security-0
26367    security-0
26368    security-0
26369    security-0
26370    security-0
26371    security-0
26372    security-0
26373    security-0
26374    security-0
26375    security-0
26376    security-0
26377    security-0
26378    security-0
26379    security-0
26380    security-0
26381    security-0
26382    security-0
26383    security-0
26384    security-0
26385    security-0
Name: security, Length: 26386, dtype: object
0        military-0
1        military-0
2        military-0
3        military-0
4        military-0
5        military-0
6        military-0
7        military-0
8        military-0
9        military-0
10       military-0
11       military-0
12       military-0
13       military-0
14       military-0
15       military-0
16       military-0
17       military-0
18       military-0
19       military-0
20       military-0
21       military-0
22       military-0
23       military-0
24       military-0
25       military-0
26       military-0
27       military-0
28       military-0
29       military-0
            ...
26356    military-0
26357    military-0
26358    military-0
26359    military-0
26360    military-0
26361    military-1
26362    military-0
26363    military-1
26364    military-0
26365    military-0
26366    military-0
26367    military-0
26368    military-0
26369    military-0
26370    military-0
26371    military-0
26372    military-0
26373    military-0
26374    military-0
26375    military-0
26376    military-0
26377    military-0
26378    military-0
26379    military-0
26380    military-0
26381    military-0
26382    military-0
26383    military-0
26384    military-1
26385    military-0
Name: military, Length: 26386, dtype: object
0        child_alone-0
1        child_alone-0
2        child_alone-0
3        child_alone-0
4        child_alone-0
5        child_alone-0
6        child_alone-0
7        child_alone-0
8        child_alone-0
9        child_alone-0
10       child_alone-0
11       child_alone-0
12       child_alone-0
13       child_alone-0
14       child_alone-0
15       child_alone-0
16       child_alone-0
17       child_alone-0
18       child_alone-0
19       child_alone-0
20       child_alone-0
21       child_alone-0
22       child_alone-0
23       child_alone-0
24       child_alone-0
25       child_alone-0
26       child_alone-0
27       child_alone-0
28       child_alone-0
29       child_alone-0
             ...
26356    child_alone-0
26357    child_alone-0
26358    child_alone-0
26359    child_alone-0
26360    child_alone-0
26361    child_alone-0
26362    child_alone-0
26363    child_alone-0
26364    child_alone-0
26365    child_alone-0
26366    child_alone-0
26367    child_alone-0
26368    child_alone-0
26369    child_alone-0
26370    child_alone-0
26371    child_alone-0
26372    child_alone-0
26373    child_alone-0
26374    child_alone-0
26375    child_alone-0
26376    child_alone-0
26377    child_alone-0
26378    child_alone-0
26379    child_alone-0
26380    child_alone-0
26381    child_alone-0
26382    child_alone-0
26383    child_alone-0
26384    child_alone-0
26385    child_alone-0
Name: child_alone, Length: 26386, dtype: object
0        water-0
1        water-0
2        water-0
3        water-0
4        water-0
5        water-0
6        water-0
7        water-1
8        water-0
9        water-0
10       water-1
11       water-0
12       water-1
13       water-0
14       water-0
15       water-1
16       water-1
17       water-0
18       water-0
19       water-0
20       water-0
21       water-0
22       water-1
23       water-0
24       water-0
25       water-0
26       water-1
27       water-0
28       water-1
29       water-0
          ...
26356    water-0
26357    water-0
26358    water-0
26359    water-0
26360    water-0
26361    water-0
26362    water-0
26363    water-0
26364    water-0
26365    water-0
26366    water-0
26367    water-1
26368    water-0
26369    water-0
26370    water-0
26371    water-0
26372    water-0
26373    water-0
26374    water-0
26375    water-0
26376    water-0
26377    water-0
26378    water-0
26379    water-0
26380    water-0
26381    water-0
26382    water-0
26383    water-0
26384    water-0
26385    water-0
Name: water, Length: 26386, dtype: object
0        food-0
1        food-0
2        food-0
3        food-0
4        food-0
5        food-0
6        food-0
7        food-0
8        food-0
9        food-0
10       food-1
11       food-0
12       food-0
13       food-1
14       food-0
15       food-1
16       food-1
17       food-0
18       food-0
19       food-0
20       food-0
21       food-0
22       food-0
23       food-1
24       food-0
25       food-0
26       food-1
27       food-0
28       food-1
29       food-0
          ...
26356    food-0
26357    food-0
26358    food-0
26359    food-0
26360    food-0
26361    food-0
26362    food-0
26363    food-0
26364    food-0
26365    food-0
26366    food-0
26367    food-0
26368    food-0
26369    food-0
26370    food-0
26371    food-0
26372    food-0
26373    food-0
26374    food-0
26375    food-0
26376    food-0
26377    food-0
26378    food-0
26379    food-0
26380    food-0
26381    food-0
26382    food-0
26383    food-0
26384    food-0
26385    food-0
Name: food, Length: 26386, dtype: object
0        shelter-0
1        shelter-0
2        shelter-0
3        shelter-0
4        shelter-0
5        shelter-0
6        shelter-0
7        shelter-1
8        shelter-0
9        shelter-0
10       shelter-0
11       shelter-0
12       shelter-0
13       shelter-0
14       shelter-0
15       shelter-1
16       shelter-0
17       shelter-0
18       shelter-0
19       shelter-0
20       shelter-0
21       shelter-0
22       shelter-0
23       shelter-0
24       shelter-0
25       shelter-0
26       shelter-0
27       shelter-0
28       shelter-0
29       shelter-0
           ...
26356    shelter-0
26357    shelter-0
26358    shelter-1
26359    shelter-0
26360    shelter-0
26361    shelter-0
26362    shelter-0
26363    shelter-0
26364    shelter-0
26365    shelter-0
26366    shelter-0
26367    shelter-0
26368    shelter-1
26369    shelter-0
26370    shelter-0
26371    shelter-0
26372    shelter-0
26373    shelter-0
26374    shelter-0
26375    shelter-0
26376    shelter-0
26377    shelter-0
26378    shelter-0
26379    shelter-0
26380    shelter-0
26381    shelter-0
26382    shelter-0
26383    shelter-0
26384    shelter-0
26385    shelter-0
Name: shelter, Length: 26386, dtype: object
0        clothing-0
1        clothing-0
2        clothing-0
3        clothing-0
4        clothing-0
5        clothing-0
6        clothing-0
7        clothing-0
8        clothing-0
9        clothing-0
10       clothing-0
11       clothing-0
12       clothing-0
13       clothing-0
14       clothing-0
15       clothing-1
16       clothing-0
17       clothing-0
18       clothing-0
19       clothing-0
20       clothing-0
21       clothing-0
22       clothing-0
23       clothing-0
24       clothing-0
25       clothing-0
26       clothing-0
27       clothing-0
28       clothing-0
29       clothing-0
            ...
26356    clothing-0
26357    clothing-0
26358    clothing-0
26359    clothing-0
26360    clothing-0
26361    clothing-0
26362    clothing-0
26363    clothing-0
26364    clothing-0
26365    clothing-0
26366    clothing-0
26367    clothing-0
26368    clothing-0
26369    clothing-0
26370    clothing-0
26371    clothing-0
26372    clothing-0
26373    clothing-0
26374    clothing-0
26375    clothing-0
26376    clothing-0
26377    clothing-0
26378    clothing-0
26379    clothing-0
26380    clothing-0
26381    clothing-0
26382    clothing-0
26383    clothing-0
26384    clothing-0
26385    clothing-0
Name: clothing, Length: 26386, dtype: object
0        money-0
1        money-0
2        money-0
3        money-0
4        money-0
5        money-0
6        money-0
7        money-0
8        money-0
9        money-0
10       money-0
11       money-0
12       money-0
13       money-0
14       money-0
15       money-0
16       money-0
17       money-0
18       money-0
19       money-0
20       money-0
21       money-0
22       money-0
23       money-0
24       money-0
25       money-0
26       money-0
27       money-0
28       money-0
29       money-0
          ...
26356    money-0
26357    money-0
26358    money-0
26359    money-0
26360    money-0
26361    money-0
26362    money-0
26363    money-0
26364    money-0
26365    money-0
26366    money-0
26367    money-0
26368    money-0
26369    money-0
26370    money-0
26371    money-0
26372    money-0
26373    money-1
26374    money-0
26375    money-0
26376    money-0
26377    money-0
26378    money-0
26379    money-0
26380    money-0
26381    money-0
26382    money-0
26383    money-0
26384    money-0
26385    money-0
Name: money, Length: 26386, dtype: object
0        missing_people-0
1        missing_people-0
2        missing_people-0
3        missing_people-0
4        missing_people-0
5        missing_people-0
6        missing_people-0
7        missing_people-0
8        missing_people-0
9        missing_people-0
10       missing_people-0
11       missing_people-0
12       missing_people-0
13       missing_people-0
14       missing_people-0

In [38]:
for column in categories:
    categories[column] = categories[column].apply(extract_bool)
    print(categories[column])

0        1
1        1
2        1
3        1
4        1
5        0
6        1
7        1
8        0
9        1
10       1
11       0
12       1
13       1
14       1
15       1
16       1
17       0
18       0
19       1
20       1
21       1
22       1
23       1
24       1
25       0
26       1
27       1
28       1
29       1
        ..
26356    1
26357    1
26358    1
26359    0
26360    0
26361    1
26362    1
26363    1
26364    1
26365    0
26366    1
26367    1
26368    1
26369    1
26370    0
26371    1
26372    1
26373    1
26374    0
26375    1
26376    1
26377    1
26378    1
26379    0
26380    1
26381    0
26382    0
26383    1
26384    1
26385    1
Name: related, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        1
8        0
9        1
10       1
11       0
12       1
13       1
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       1
22       1
23       1
24       0
25       0
26       1
27       1
28       1
29       1
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    1
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: request, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: offer, Length: 26386, dtype: object
0        0
1        1
2        0
3        1
4        0
5        0
6        0
7        1
8        0
9        1
10       1
11       0
12       1
13       1
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       1
22       1
23       1
24       0
25       0
26       1
27       1
28       1
29       1
        ..
26356    1
26357    1
26358    1
26359    0
26360    0
26361    1
26362    0
26363    1
26364    0
26365    0
26366    0
26367    1
26368    1
26369    1
26370    0
26371    0
26372    0
26373    1
26374    0
26375    1
26376    1
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    1
26385    0
Name: aid_related, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        1
10       1
11       0
12       0
13       0
14       0
15       0
16       1
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       1
27       1
28       0
29       0
        ..
26356    1
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    1
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: medical_help, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        1
10       1
11       0
12       0
13       0
14       0
15       1
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       1
27       0
28       0
29       0
        ..
26356    0
26357    1
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    1
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    1
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: medical_products, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    1
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: search_and_rescue, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: security, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    1
26362    0
26363    1
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    1
26385    0
Name: military, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: child_alone, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        1
8        0
9        0
10       1
11       0
12       1
13       0
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       0
22       1
23       0
24       0
25       0
26       1
27       0
28       1
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    1
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: water, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       1
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       0
22       0
23       1
24       0
25       0
26       1
27       0
28       1
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: food, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        1
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       1
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    1
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    1
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: shelter, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       1
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: clothing, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    1
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: money, Length: 26386, dtype: object

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: missing_people, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    1
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    1
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: refugees, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: death, Length: 26386, dtype: object
0        0
1        1
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       1
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       1
        ..
26356    0
26357    1
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    1
26370    0
26371    0
26372    0
26373    1
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: other_aid, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    1
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: infrastructure_related, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    1
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: transport, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: buildings, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    1
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: electricity, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: tools, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    1
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: hospitals, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: shops, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: aid_centers, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: other_infrastructure, Length: 26386, dtype: object
0        0
1        1
2        0
3        0
4        0
5        0
6        1
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       1
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    1
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    1
26372    0
26373    1
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: weather_related, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    1
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    1
26372    0
26373    1
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: floods, Length: 26386, dtype: object
0        0
1        1
2        0
3        0
4        0
5        0
6        1
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: storm, Length: 26386, dtype: object

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    1
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: fire, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       1
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: earthquake, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: cold, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    1
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: other_weather, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        1
8        0
9        1
10       1
11       0
12       1
13       1
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       1
22       1
23       0
24       0
25       0
26       1
27       1
28       1
29       1
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    1
26368    1
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    1
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: direct_report, Length: 26386, dtype: object

In [39]:
for column in categories:
    # set each value to be the last character of the string
    categories[column] = categories[column].apply(extract_bool)
    print(categories[column])
    # convert column from string to numeric
    categories[column] = categories[column].astype('float')
categories.head()

0        1
1        1
2        1
3        1
4        1
5        0
6        1
7        1
8        0
9        1
10       1
11       0
12       1
13       1
14       1
15       1
16       1
17       0
18       0
19       1
20       1
21       1
22       1
23       1
24       1
25       0
26       1
27       1
28       1
29       1
        ..
26356    1
26357    1
26358    1
26359    0
26360    0
26361    1
26362    1
26363    1
26364    1
26365    0
26366    1
26367    1
26368    1
26369    1
26370    0
26371    1
26372    1
26373    1
26374    0
26375    1
26376    1
26377    1
26378    1
26379    0
26380    1
26381    0
26382    0
26383    1
26384    1
26385    1
Name: related, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        1
8        0
9        1
10       1
11       0
12       1
13       1
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       1
22       1
23       1
24       0
25       0
26       1
27       1
28       1
29       1
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    1
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: request, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: offer, Length: 26386, dtype: object
0        0
1        1
2        0
3        1
4        0
5        0
6        0
7        1
8        0
9        1
10       1
11       0
12       1
13       1
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       1
22       1
23       1
24       0
25       0
26       1
27       1
28       1
29       1
        ..
26356    1
26357    1
26358    1
26359    0
26360    0
26361    1
26362    0
26363    1
26364    0
26365    0
26366    0
26367    1
26368    1
26369    1
26370    0
26371    0
26372    0
26373    1
26374    0
26375    1
26376    1
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    1
26385    0
Name: aid_related, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        1
10       1
11       0
12       0
13       0
14       0
15       0
16       1
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       1
27       1
28       0
29       0
        ..
26356    1
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    1
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: medical_help, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        1
10       1
11       0
12       0
13       0
14       0
15       1
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       1
27       0
28       0
29       0
        ..
26356    0
26357    1
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    1
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    1
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: medical_products, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    1
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: search_and_rescue, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: security, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    1
26362    0
26363    1
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    1
26385    0
Name: military, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: child_alone, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        1
8        0
9        0
10       1
11       0
12       1
13       0
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       0
22       1
23       0
24       0
25       0
26       1
27       0
28       1
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    1
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: water, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       1
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       0
22       0
23       1
24       0
25       0
26       1
27       0
28       1
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: food, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        1
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       1
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    1
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    1
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: shelter, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       1
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: clothing, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    1
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: money, Length: 26386, dtype: object

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: missing_people, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    1
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    1
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: refugees, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: death, Length: 26386, dtype: object
0        0
1        1
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       1
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       1
        ..
26356    0
26357    1
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    1
26370    0
26371    0
26372    0
26373    1
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: other_aid, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    1
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: infrastructure_related, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    1
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: transport, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: buildings, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    1
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: electricity, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: tools, Length: 26386, dtype: object
0        0
1        0
2        0
3        1
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    1
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: hospitals, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: shops, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: aid_centers, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: other_infrastructure, Length: 26386, dtype: object
0        0
1        1
2        0
3        0
4        0
5        0
6        1
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       1
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    1
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    1
26372    0
26373    1
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: weather_related, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       1
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       1
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    1
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    1
26372    0
26373    1
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: floods, Length: 26386, dtype: object
0        0
1        1
2        0
3        0
4        0
5        0
6        1
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: storm, Length: 26386, dtype: object

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    1
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: fire, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       1
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: earthquake, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: cold, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    1
26365    0
26366    0
26367    0
26368    0
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    0
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: other_weather, Length: 26386, dtype: object
0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        1
8        0
9        1
10       1
11       0
12       1
13       1
14       0
15       1
16       1
17       0
18       0
19       0
20       0
21       1
22       1
23       0
24       0
25       0
26       1
27       1
28       1
29       1
        ..
26356    0
26357    0
26358    0
26359    0
26360    0
26361    0
26362    0
26363    0
26364    0
26365    0
26366    0
26367    1
26368    1
26369    0
26370    0
26371    0
26372    0
26373    0
26374    0
26375    0
26376    0
26377    1
26378    0
26379    0
26380    0
26381    0
26382    0
26383    0
26384    0
26385    0
Name: direct_report, Length: 26386, dtype: object

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
#categories.select_dtypes(include='number')

In [48]:
#categories.select_dtypes(include='category').columns.nunique()

In [41]:
categories.select_dtypes(include='number').columns.nunique()

36

### 5. Replace `categories` column in `df` with new category columns.
- Drop the categories column from the df dataframe since it is no longer needed.
- Concatenate df and categories data frames.

In [45]:
categories.columns.nunique()

36

In [49]:
df.columns

Index(['id', 'message', 'original', 'genre', 'categories'], dtype='object')

In [50]:
# drop the original categories column from `df`
df = df.drop(columns='categories')

df.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [51]:
# concatenate the original dataframe with the new `categories` dataframe
df = pd.concat([df, categories], axis=1)
df.head()

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,1.0,1.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
df.select_dtypes(include='number').columns.nunique()

37

In [63]:
df.select_dtypes(include='object').columns.nunique()

3

### 6. Remove duplicates.
- Check how many duplicates are in this dataset.
- Drop the duplicates.
- Confirm duplicates were removed.

In [73]:
# check number of duplicates

df.duplicated().sum()

0

In [70]:
#df[df.duplicated()]

In [71]:
# drop duplicates

df = df.drop_duplicates()

In [72]:
# check number of duplicates

df.duplicated().sum()

0

### 7. Save the clean dataset into an sqlite database.
You can do this with pandas [`to_sql` method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html) combined with the SQLAlchemy library. Remember to import SQLAlchemy's `create_engine` in the first cell of this notebook to use it below.

In [74]:
engine = create_engine('sqlite:///InsertDatabaseName.db')
df.to_sql('process_data_table', engine, index=False)

### 8. Use this notebook to complete `process_data.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database based on new datasets specified by the user. Alternatively, you can complete `process_data.py` in the classroom on the `Project Workspace IDE` coming later.